export const newProducts = [
    {
      Id: 1,
      Name: "Öne Çıkanlar",
      Parent: null,
      Children: [
        {
          Id: 1000,
          Name: "Tüm Yeni Sezon Ürünlerini İncele",
          Parent: 1,
          Children: [],
        },
        {
          Id: 1001,
          Name: "SNKRS Lansman Takvimi",
          Parent: 1,
          Children: [],
        },
      ],
    },
    {
      Id: 2,
      Name: "Yeni Erkek Ürünleri",
      Parent: null,
      Children: [
        {
          Id: 2000,
          Name: "Ayakkabılar",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2001,
          Name: "Giysiler",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2002,
          Name: "Ekipmanlar",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2003,
          Name: "Tüm Yeni Erkek Ürünlerini İncele",
          Parent: 2,
          Children: [],
        },
      ],
    },
    {
      Id: 3,
      Name: "Yeni Kadın Ürünleri",
      Parent: null,
      Children: [
        {
          Id: 3000,
          Name: "Ayakkabılar",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3001,
          Name: "Giysiler",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3002,
          Name: "Ekipmanlar",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3003,
          Name: "Tüm Yeni Kadın Ürünlerini İncele",
          Parent: 3,
          Children: [],
        },
      ],
    },
    {
      Id: 4,
      Name: "Yeni Çocuk Ürünleri",
      Parent: null,
      Children: [
        {
          Id: 4000,
          Name: "Erkek Çocuk Ayakkabıları",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4001,
          Name: "Erkek Çocuk Giysileri",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4002,
          Name: "Kız Çocuk Ayakkabıları",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4003,
          Name: "Kız Çocuk Giysileri",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4004,
          Name: "Tüm Yeni Çocuk Ürünlerini İncele",
          Parent: 4,
          Children: [],
        },
      ],
    },
    {
      Id: 5,
      Name: "Markaya Göre İncele",
      Parent: null,
      Children: [
        {
          Id: 5000,
          Name: "Nike Sportswear",
          Parent: 5,
          Children: [],
        },
        {
          Id: 5001,
          Name: "NikeLab",
          Parent: 5,
          Children: [],
        },
        {
          Id: 5002,
          Name: "Jordan",
          Parent: 5,
          Children: [],
        },
        {
          Id: 5003,
          Name: "Nike SB",
          Parent: 5,
          Children: [],
        },
        {
          Id: 5004,
          Name: "ACG",
          Parent: 5,
          Children: [],
        },
        {
          Id: 5005,
          Name: "Nike Pro",
          Parent: 5,
          Children: [],
        },
      ],
    },
  ];

 export  const manProducts = [
    {
      Id: 1,
      Name: "Öne Çıkanlar",
      Parent: null,
      Children: [
        {
          Id: 1000,
          Name: "Yeni Çıkanlar",
          Parent: 1,
          Children: [],
        },
        {
          Id: 1001,
          Name: "İlkbaharın Başlangıcı",
          Parent: 1,
          Children: [],
        },
        {
          Id: 1002,
          Name: "SNKRS Lansman Takvimi",
          Parent: 1,
          Children: [],
        },
        {
          Id: 1003,
          Name: "Üye Erişimi",
          Parent: 1,
          Children: [],
        },
        {
          Id: 1004,
          Name: "En Çok Satanlar",
          Parent: 1,
          Children: [],
        },
        {
          Id: 1005,
          Name: "Sürdürülebilir Malzemeler",
          Parent: 1,
          Children: [],
        },
        {
          Id: 1006,
          Name: "Temel Nike Ürünleri",
          Parent: 1,
          Children: [],
        },
      ],
    },
    {
      Id: 2,
      Name: "Ayakkabılar",
      Parent: null,
      Children: [
        {
          Id: 2000,
          Name: "Tüm Ayakkabılar",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2001,
          Name: "İndirimdeki Tüm Ayakkabılar",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2002,
          Name: "Günlük Giyim",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2003,
          Name: "Koşu",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2004,
          Name: "Basketbol",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2005,
          Name: "Futbol",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2006,
          Name: "Jordan",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2007,
          Name: "Spor Salonu Ve Antrenman",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2008,
          Name: "Kaykay",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2009,
          Name: "Tenis",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2010,
          Name: "Golf",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2011,
          Name: "Nike By You ile Kişiselleştir",
          Parent: 2,
          Children: [],
        },
      ],
    },
    {
      Id: 3,
      Name: "Giysiler",
      Parent: null,
      Children: [
        {
          Id: 3000,
          Name: "Tüm Giysiler",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3001,
          Name: "İndirimdeki Tüm Giysiler",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3002,
          Name: "Kapüşonlu Üstler ve Sweatshirt'ler",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3003,
          Name: "Üstler ve Tişörtler",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3004,
          Name: "Eşofman Altları ve Taytlar",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3005,
          Name: "Eşofmanlar",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3006,
          Name: "Uyumlu Setler",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3007,
          Name: "Şortlar",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3008,
          Name: "Ceketler ve Yelekler",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3009,
          Name: "Formalar",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3010,
          Name: "Polo Üstler",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3011,
          Name: "Büyük Beden ve Uzun Boy",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3012,
          Name: "Çoraplar",
          Parent: 3,
          Children: [],
        },
      ],
    },
    {
      Id: 4,
      Name: "Spora Göre İncele",
      Parent: null,
      Children: [
        {
          Id: 4000,
          Name: "Koşu",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4001,
          Name: "Futbol",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4002,
          Name: "Basketbol",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4003,
          Name: "Tenis",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4004,
          Name: "Golf",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4005,
          Name: "Spor Salonu ve Antrenman",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4006,
          Name: "Cross Training",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4007,
          Name: "Kaykay",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4008,
          Name: "Yoga",
          Parent: 4,
          Children: [],
        },
      ],
    },
  ];


 export  const womanProducts = [
    {
      Id: 1,
      Name: "Öne Çıkanlar",
      Parent: null,
      Children: [
        {
          Id: 1000,
          Name: "Yeni Çıkanlar",
          Parent: 1,
          Children: [],
        },
        {
          Id: 1001,
          Name: "İlkbaharın Başlangıcı",
          Parent: 1,
          Children: [],
        },
        {
          Id: 1002,
          Name: "SNKRS Lansman Takvimi",
          Parent: 1,
          Children: [],
        },
        {
          Id: 1003,
          Name: "Üye Erişimi",
          Parent: 1,
          Children: [],
        },
        {
          Id: 1004,
          Name: "En Çok Satanlar",
          Parent: 1,
          Children: [],
        },
        {
          Id: 1005,
          Name: "Sürdürülebilir Malzemeler",
          Parent: 1,
          Children: [],
        },
        {
          Id: 1006,
          Name: "Temel Nike Ürünleri",
          Parent: 1,
          Children: [],
        },
      ],
    },
    {
      Id: 2,
      Name: "Ayakkabılar",
      Parent: null,
      Children: [
        {
          Id: 2000,
          Name: "Tüm Ayakkabılar",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2001,
          Name: "İndirimdeki Tüm Ayakkabılar",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2002,
          Name: "Günlük Giyim",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2003,
          Name: "Koşu",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2004,
          Name: "Basketbol",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2005,
          Name: "Futbol",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2006,
          Name: "Jordan",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2007,
          Name: "Spor Salonu Ve Antrenman",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2008,
          Name: "Kaykay",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2009,
          Name: "Tenis",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2010,
          Name: "Golf",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2011,
          Name: "Nike By You ile Kişiselleştir",
          Parent: 2,
          Children: [],
        },
      ],
    },
    {
      Id: 3,
      Name: "Giysiler",
      Parent: null,
      Children: [
        {
          Id: 3000,
          Name: "Tüm Giysiler",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3001,
          Name: "İndirimdeki Tüm Giysiler",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3002,
          Name: "Kapüşonlu Üstler ve Sweatshirt'ler",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3003,
          Name: "Üstler ve Tişörtler",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3004,
          Name: "Eşofman Altları ve Taytlar",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3005,
          Name: "Eşofmanlar",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3006,
          Name: "Uyumlu Setler",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3007,
          Name: "Şortlar",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3008,
          Name: "Ceketler ve Yelekler",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3009,
          Name: "Formalar",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3010,
          Name: "Polo Üstler",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3011,
          Name: "Büyük Beden ve Uzun Boy",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3012,
          Name: "Çoraplar",
          Parent: 3,
          Children: [],
        },
      ],
    },
    {
      Id: 4,
      Name: "Spora Göre İncele",
      Parent: null,
      Children: [
        {
          Id: 4000,
          Name: "Koşu",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4001,
          Name: "Futbol",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4002,
          Name: "Basketbol",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4003,
          Name: "Tenis",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4004,
          Name: "Golf",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4005,
          Name: "Spor Salonu ve Antrenman",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4006,
          Name: "Cross Training",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4007,
          Name: "Kaykay",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4008,
          Name: "Yoga",
          Parent: 4,
          Children: [],
        },
      ],
    },
  ];


  export  const kidProducts = [
    {
      Id: 1,
      Name: "Öne Çıkanlar",
      Parent: null,
      Children: [
        {
          Id: 1000,
          Name: "Yeni Çıkanlar",
          Parent: 1,
          Children: [],
        },
        {
          Id: 1001,
          Name: "İlkbaharın Başlangıcı",
          Parent: 1,
          Children: [],
        },
        {
          Id: 1002,
          Name: "Fleece",
          Parent: 1,
          Children: [],
        },
        {
          Id: 1003,
          Name: "Spor Ekipmanları",
          Parent: 1,
          Children: [],
        },
        {
          Id: 1004,
          Name: "Dans",
          Parent: 1,
          Children: [],
        },
        {
          Id: 1005,
          Name: "En Çok Satanlar",
          Parent: 1,
          Children: [],
        },
        {
          Id: 1006,
          Name: "Sürdürülebilir Malzemeler",
          Parent: 1,
          Children: [],
        },
      ],
    },
    {
      Id: 2,
      Name: "Ayakkabılar",
      Parent: null,
      Children: [
        {
          Id: 2000,
          Name: "Tüm Ayakkabılar",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2001,
          Name: "Tüm Spor Ayakkabıları",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2002,
          Name: "Bebek (17-27)",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2003,
          Name: "Küçük Çocuk (27,5-35)",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2004,
          Name: "Genç Çocuk (35,5-40)",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2005,
          Name: "Günlük Giyim",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2006,
          Name: "Futbol",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2007,
          Name: "Koşu",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2008,
          Name: "Jordan",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2009,
          Name: "Air Max",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2010,
          Name: "Air Force 1",
          Parent: 2,
          Children: [],
        },
      ],
    },
    {
      Id: 3,
      Name: "Erkek Çocuk Giysileri",
      Parent: null,
      Children: [
        {
          Id: 3000,
          Name: "Tüm Erkek Çocuk Giysileri",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3001,
          Name: "Bebek (0-36 Ay)",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3002,
          Name: "Küçük Çocuk (96-128 CM)",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3003,
          Name: "Genç Çocuk (122-170 CM)",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3004,
          Name: "Spor Giysileri",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3005,
          Name: "Kapüşonlu Üstler ve Sweatshirt'ler",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3006,
          Name: "Eşofman Altları ve Taytlar",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3007,
          Name: "Eşofmanlar",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3008,
          Name: "Ceketler ve Yelekler",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3009,
          Name: "Üstler ve Tişörtler",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3010,
          Name: "Şortlar",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3011,
          Name: "Formalar",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3012,
          Name: "Çoraplar",
          Parent: 3,
          Children: [],
        },
      ],
    },
    {
      Id: 4,
      Name: "Kız Çocuk Giysileri",
      Parent: null,
      Children: [
        {
          Id: 4000,
          Name: "Tüm Kız Çocuk Giysileri",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4001,
          Name: "Bebek (0-36 Ay)",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4002,
          Name: "Küçük Çocuk (96-128 CM)",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4003,
          Name: "Genç Çocuk (122-170 CM)",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4004,
          Name: "Spor Giysileri",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4005,
          Name: "Spor Sütyenleri",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4006,
          Name: "Kapüşonlu Üstler ve Sweatshirt'ler",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4007,
          Name: "Eşofman Altları ve Taytlar",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4008,
          Name: "Eşofmanlar",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4009,
          Name: "Ceketler ve Yelekler",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4010,
          Name: "Şortlar",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4011,
          Name: "Etekler ve Elbiseler",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4012,
          Name: "Formalar",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4013,
          Name: "Çoraplar",
          Parent: 4,
          Children: [],
        },
      ],
    },
    {
      Id: 5,
      Name: "Bebek",
      Parent: null,
      Children: [
        {
          Id: 5000,
          Name: "Kız Bebek",
          Parent: 5,
          Children: [],
        },
        {
          Id: 5001,
          Name: "Erkek Bebek",
          Parent: 5,
          Children: [],
        },
        {
          Id: 5002,
          Name: "Tüm Bebek Ayakkabıları",
          Parent: 5,
          Children: [],
        },
        {
          Id: 5003,
          Name: "Tüm Bebek Giysileri",
          Parent: 5,
          Children: [],
        },
        {
          Id: 5004,
          Name: "Bebek Setleri",
          Parent: 5,
          Children: [],
        },
      ],
    },
  ];


  export  const saleProducts = [
    {
      Id: 1,
      Name: "Öne Çıkanlar",
      Parent: null,
      Children: [
        {
          Id: 1000,
          Name: "Tüm İndirimli Ürünleri İncele",
          Parent: 1,
          Children: [],
        },
        {
          Id: 1001,
          Name: "Kış Stilleri İndirimi",
          Parent: 1,
          Children: [],
        },
      ],
    },
    {
      Id: 2,
      Name: "Erkekler İçin İndirimli Ürünler",
      Parent: null,
      Children: [
        {
          Id: 2000,
          Name: "Erkekler İçin En Çok Satanlar",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2001,
          Name: "Ayakkabılar",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2002,
          Name: "Giysiler",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2003,
          Name: "Aksesuarlar ve Ekipmanlar",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2004,
          Name: "Kapüşonlu Üstler ve Sweatshirt'ler",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2005,
          Name: "Eşofman Altları ve Taytlar",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2006,
          Name: "Ceketler ve Yelekler",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2007,
          Name: "Tüm İndirimli Erkek Ürünlerini İncele",
          Parent: 2,
          Children: [],
        },
      ],
    },
    {
      Id: 3,
      Name: "Kadınlar İçin İndirimli Ürünler",
      Parent: null,
      Children: [
        {
          Id: 3000,
          Name: "Kadınlar İçin En Çok Satanlar",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3001,
          Name: "Ayakkabılar",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3002,
          Name: "Giysiler",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3003,
          Name: "Aksesuarlar ve Ekipmanlar",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3004,
          Name: "Kapüşonlu Üstler ve Sweatshirt'ler",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3005,
          Name: "Eşofman Altları ve Taytlar",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3006,
          Name: "Ceketler ve Yelekler",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3007,
          Name: "Spor Sütyenleri",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3008,
          Name: "Tüm İndirimli Kadın Ürünlerini İncele",
          Parent: 3,
          Children: [],
        },
      ],
    },
    {
      Id: 4,
      Name: "Çocuklar İçin İndirimli Ürünler",
      Parent: null,
      Children: [
        {
          Id: 4000,
          Name: "Çocuklar İçin En Çok Satanlar",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4001,
          Name: "Ayakkabılar",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4002,
          Name: "Giysiler",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4003,
          Name: "Aksesuarlar ve Ekipmanlar",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4004,
          Name: "Kapüşonlu Üstler ve Sweatshirt'ler",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4005,
          Name: "Eşofman Altları ve Taytlar",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4006,
          Name: "Ceketler ve Yelekler",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4007,
          Name: "Spor Sütyenleri",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4008,
          Name: "Tüm İndirimli Çocuk Ürünlerini İncele",
          Parent: 4,
          Children: [],
        },
      ],
    },
    {
      Id: 5,
      Name: "Spora Göre İndirimli Ürünler",
      Parent: null,
      Children: [
        {
          Id: 5000,
          Name: "Koşu",
          Parent: 5,
          Children: [],
        },
        {
          Id: 5001,
          Name: "Spor Salonu ve Antrenman",
          Parent: 5,
          Children: [],
        },
        {
          Id: 5002,
          Name: "Yoga",
          Parent: 5,
          Children: [],
        },
        {
          Id: 5003,
          Name: "Futbol",
          Parent: 5,
          Children: [],
        },
        {
          Id: 5004,
          Name: "Basketbol",
          Parent: 5,
          Children: [],
        },
        {
          Id: 5005,
          Name: "Tenis",
          Parent: 5,
          Children: [],
        },
        {
          Id: 5006,
          Name: "Golf",
          Parent: 5,
          Children: [],
        },
      ],
    },
  ];

  export  const collectionProducts = [
    {
      Id: 1,
      Name: "Trend Ürünler",
      Parent: null,
      Children: [
        {
          Id: 1000,
          Name: "Air Ayakkabılar",
          Parent: 1,
          Children: [],
        },
        {
          Id: 1001,
          Name: "FlyEase",
          Parent: 1,
          Children: [],
        },
        {
          Id: 1002,
          Name: "Flyknit",
          Parent: 1,
          Children: [],
        },
        {
          Id: 1003,
          Name: "Nike Free",
          Parent: 1,
          Children: [],
        },
        {
          Id: 1004,
          Name: "Metcon",
          Parent: 1,
          Children: [],
        },
        {
          Id: 1005,
          Name: "Air Zoom",
          Parent: 1,
          Children: [],
        },
        {
          Id: 1006,
          Name: "FlyEase",
          Parent: 1,
          Children: [],
        },
        {
          Id: 1007,
          Name: "SB Janoski",
          Parent: 1,
          Children: [],
        },
        {
          Id: 1008,
          Name: "Jordan X Paris Saint-Germain",
          Parent: 1,
          Children: [],
        },
        {
          Id: 1009,
          Name: "LeBron James Ayakkabıları",
          Parent: 1,
          Children: [],
        },
        {
          Id: 1010,
          Name: "SuperRep Ayakkabılar",
          Parent: 1,
          Children: [],
        },
        {
          Id: 1011,
          Name: "Kadınlar İçin Air Force 1",
          Parent: 1,
          Children: [],
        },
        {
          Id: 1012,
          Name: "Beyaz Air Force 1",
          Parent: 1,
          Children: [],
        },
        {
          Id: 1013,
          Name: "Netbol",
          Parent: 1,
          Children: [],
        },
        {
          Id: 1014,
          Name: "Temel Nike Ürünleri",
          Parent: 1,
          Children: [],
        },
      ],
    },
    {
      Id: 2,
      Name: "Günlük Giyim",
      Parent: null,
      Children: [
        {
          Id: 2000,
          Name: "Air Force 1",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2001,
          Name: "Blazer",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2002,
          Name: "Air Max",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2003,
          Name: "Air Max 1",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2004,
          Name: "Air Max 90",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2005,
          Name: "Air Max 95",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2006,
          Name: "Air Max 97",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2007,
          Name: "Air Max 270",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2008,
          Name: "Air Max 720",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2009,
          Name: "Air Max 2090",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2010,
          Name: "Air Max Plus",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2011,
          Name: "VaporMax",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2012,
          Name: "Staple Kicks",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2013,
          Name: "Cortez",
          Parent: 2,
          Children: [],
        },
        {
          Id: 2014,
          Name: "Air Jordan 1",
          Parent: 2,
          Children: [],
        },
      ],
    },
    {
      Id: 3,
      Name: "Koşu",
      Parent: null,
      Children: [
        {
          Id: 3000,
          Name: "Joyride",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3001,
          Name: "React",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3002,
          Name: "Pegasus",
          Parent: 3,
          Children: [],
        },
        {
          Id: 3003,
          Name: "Air Zoom",
          Parent: 3,
          Children: [],
        },
      ],
    },
    {
      Id: 4,
      Name: "Futbol",
      Parent: null,
      Children: [
        {
          Id: 4000,
          Name: "Phantom",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4001,
          Name: "Mercurial",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4002,
          Name: "Tiempo",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4003,
          Name: "Futsal",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4004,
          Name: "Kişiye Özel Formalar",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4005,
          Name: "Milli Takım Koleksiyonu",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4006,
          Name: "Futbol Kulüpleri",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4007,
          Name: "F.C. Barcelona",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4008,
          Name: "Liverpool F.C.",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4009,
          Name: "Paris Saint-Germain",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4010,
          Name: "Chelsea",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4011,
          Name: "Tottenham Hotspur",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4012,
          Name: "Nike Football Training",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4013,
          Name: "Cristiano Ronaldo",
          Parent: 4,
          Children: [],
        },
        {
          Id: 4014,
          Name: "Inter Milan",
          Parent: 4,
          Children: [],
        },
      ],
    },
    {
      Id: 5,
      Name: "Spora Göre İndirimli Ürünler",
      Parent: null,
      Children: [
        {
          Id: 5000,
          Name: "Koşu",
          Parent: 5,
          Children: [],
        },
        {
          Id: 5001,
          Name: "Spor Salonu ve Antrenman",
          Parent: 5,
          Children: [],
        },
        {
          Id: 5002,
          Name: "Yoga",
          Parent: 5,
          Children: [],
        },
        {
          Id: 5003,
          Name: "Futbol",
          Parent: 5,
          Children: [],
        },
        {
          Id: 5004,
          Name: "Basketbol",
          Parent: 5,
          Children: [],
        },
        {
          Id: 5005,
          Name: "Tenis",
          Parent: 5,
          Children: [],
        },
        {
          Id: 5006,
          Name: "Golf",
          Parent: 5,
          Children: [],
        },
      ],
    },
  ];
